pipeline {
    agent any
    stages {
        stage('Start'){
            steps {
                echo 'This is the start of the Build!'
            }
        }
        stage('Build') {
            steps {
                sh 'i/usr/bin/mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/usr/bin/mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
