pipeline {
    agent any
    stages {
        stage('Start'){
            steps {
                echo 'This is the start of the Build!'
            }
        }
        stage('Build') {
            steps {
                sh '''
                    export JAVA_HOME=/usr/lib/jvm/default-java
                    export M2_HOME=/opt/maven
                    export MAVEN_HOME=/opt/maven
                    export PATH=${M2_HOME}/bin:${PATH}
                    mvn -B -DskipTests clean package
                '''
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
